### PR TITLE
Install Grafana without proxy in the case that OAuth is disabled but Grafana is enabled

### PR DESCRIPTION
**Pull request by cunningt**
If you choose to deselect the Oauth checkbox, but leave the Grafana checkbox checked, Grafana is not installed.    Grafana should be installed in this case, without a proxy.    

I had trouble getting the datasource creation working though - I'll add that in a later PR if I can get it working.

### CODE REVIEW

**Comment by cunningt** [comment]
@jparrill It looks like the tests here failed because --version is no longer a command line option 👍 

$ oc cluster up --version=$OPENSHIFT_VERSION
Error: unknown flag: --version

**Comment by jparrill** [comment]
LGTM @dymurray could you please proceed to the merge and update the upstream image? :)

**Comment by cunningt** [comment]
@jparrill @dymurray Could we get this merged?

**Comment by cunningt** [comment]
@jparrill @dymurray This has been sitting out there for a while - any way we can get it merged?

**Pull request merged**
